### ISSUE TITLE
Typo in Section 7 Point 3

### ISSUE THREAD

**Issue by travischoma** [sysapps/app-uri#26]
Section 7 - Point 3 reads:
The developer should not be bother as to wether they are using http:// or app:// - the Web's capabilities and APIs need to just work! 

Should be:

The developer should not be _bothered_ as to _whether_ they are using http:// or app:// - the Web's capabilities and APIs need to just work!

**Comment by marcoscaceres** [comment]
@sixbit, thanks! PR is here: 
https://github.com/sysapps/app-uri/pull/27
