### ISSUE TITLE
How window.location.host of application should be treated, case insensitive or sensitive?

### ISSUE THREAD

**Issue by martap** [sysapps/app-uri#29]
In [IRI](http://tools.ietf.org/html/rfc3987) spec domain is case insensitive and I'm wondering if in our case we should treat window.location.host as domain or as path?

Generally when getting files from package using XHR host (i.e. f15a6d20-cefa-13e5-1972-800e20d19a76), host functionally to me is more like domain (case sensitive) than path.

If we should treat host case sensitive then we should mention that in specification explicitly since as it is now I expect app scheme will work similarly to http, and it that case host should be case insensitive.

What do you think?

**Comment by jmajnert** [comment]
What about all other normalizations that apply to regular IRIs, like character or percent-encoding ? Should we mention somewhere that app URI should comform to some specific URI standard, or is it too complicated?

**Comment by marcoscaceres** [comment]
On Thursday, July 18, 2013 at 3:03 PM, jmajnert wrote:

> What about all other normalizations that apply to regular IRIs, like character or percent-encoding ? Should we mention somewhere that app URI should comform to some specific URI standard, or is it too complicated?

I want to layer the app:// URI spec on top of http://url.spec.whatwg.org. In theory, that should address all of the above.

**Comment by marcoscaceres** [comment]
I don't want us to have to special case this scheme, particularly not the host part. 

@jmajnert I think the questions you had should be addressed in the [URL spec](http://url.spec.whatwg.org/) - I don't know how to answer them.

**Comment by marcoscaceres** [comment]
Closing for now and let's see if this comes up as an issue in practice. Otherwise, we can add tests for this.
